# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'style2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 754, 510))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_GetData = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_GetData.setObjectName("pushButton_GetData")
        self.gridLayout_2.addWidget(self.pushButton_GetData, 3, 1, 1, 1)


        self.pushButton_GetLinks = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_GetLinks.setObjectName("pushButton_GetLinks")
        self.gridLayout_2.addWidget(self.pushButton_GetLinks, 3, 2, 1, 1)

        self.label_Type = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Type.setObjectName("label_Type")
        self.gridLayout_2.addWidget(self.label_Type, 0, 0, 1, 1)
        self.label_Link = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Link.setObjectName("label_Link")
        self.gridLayout_2.addWidget(self.label_Link, 1, 0, 1, 1)
        self.lineEdit_Link = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Link.setObjectName("lineEdit_Link")
        self.gridLayout_2.addWidget(self.lineEdit_Link, 1, 1, 1, 1)
        self.label_SaveTo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_SaveTo.setObjectName("label_SaveTo")
        self.gridLayout_2.addWidget(self.label_SaveTo, 2, 0, 1, 1)
        self.lineEdit_SaveTo = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_SaveTo.setObjectName("lineEdit_SaveTo")
        self.gridLayout_2.addWidget(self.lineEdit_SaveTo, 2, 1, 1, 1)
        self.pushButton_SavePath = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_SavePath.setObjectName("pushButton_SavePath")
        self.gridLayout_2.addWidget(self.pushButton_SavePath, 2, 2, 1, 1)
        self.comboBox_Type = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_Type, 0, 1, 1, 1)
        self.pushButton_LinkPath = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_LinkPath.setObjectName("pushButton_LinkPath")
        self.gridLayout_2.addWidget(self.pushButton_LinkPath, 1, 2, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 734, 377))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_Data = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Data.setObjectName("label_Data")
        self.label_Data.setWordWrap(True)
        self.gridLayout_3.addWidget(self.label_Data, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea_2, 4, 0, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Parser"))
        self.pushButton_GetData.setText(_translate("MainWindow", "Get data"))
        self.pushButton_GetLinks.setText(_translate("MainWindow", "Get links"))
        self.label_Type.setText(_translate("MainWindow", "Type"))
        self.comboBox_Type.setItemText(0, _translate("MainWindow", "HTML"))
        self.comboBox_Type.setItemText(1, _translate("MainWindow", "Document"))
        self.label_Link.setText(_translate("MainWindow", "Link"))
        self.label_SaveTo.setText(_translate("MainWindow", "Save to"))
        self.pushButton_SavePath.setText(_translate("MainWindow", "To..."))
        self.pushButton_LinkPath.setText(_translate("MainWindow", "From..."))
        self.label_Data.setText(_translate("MainWindow", "The result will be displayed here..."))
